version: '3'

services:
  postgresql:
    image: postgres:9.6.17-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
